version: "3.8"

services:
  frontend:
    image: sermalenk/skypro-front:lesson-38
    ports:
      - "800:80"
    depends_on:
      api:
        condition: service_started

  api:
    build: .
    env_file:
      - .env
    environment:
      - POSTGRES_HOST=db
      - POSTGRES_PORT=5432
    ports:
      - "8000:8000"
    depends_on:
      db:
        condition: service_healthy
      migrations:
        condition: service_completed_successfully

  bot:
    build: .
    env_file:
      - .env
    environment:
      - POSTGRES_HOST=db
      - POSTGRES_PORT=5432
    depends_on:
      db:
        condition: service_healthy
      migrations:
        condition: service_completed_successfully
    command: python manage.py run_bot

  migrations:
    build: .
    env_file:
      - .env
    environment:
      - POSTGRES_HOST=db
      - POSTGRES_PORT=5432
    depends_on:
      db:
        condition: service_healthy
    command: python manage.py migrate

  db:
    image: postgres:15.2
    ports:
      - "5555:5432"
    env_file:
      - .env
    healthcheck:
      test: pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}
      interval: 3s
      retries: 10
      timeout: 3s
    restart: always
    volumes:
      - pg_data:/var/lib/postgresql/data/
volumes:
  pg_data: